#NUMPY ASSIGNMENT

#solution

In [4]:
import numpy as np
student_score = [
    [86, 92, 78, 96, 88],
    [79, 85, 91, 87, 83],
    [92, 88, 95, 91, 89],
    [76, 82, 79, 85, 81],
    [88, 91, 87, 93, 90]
])

# Convert to NumPy array
scores = np.array(student_scores)
#Explore properties
print("Array:\n", scores)
print("\nShape:", scores.shape)
print("Dimentions:", scores.ndim)
print("Data type:", scores.dtype)
print("Total elements:", scores.size)

# Basic statistics
print("\nMean (overall):",
      scores.mean())
print("Min value:", scores.min())
print("Max value:", scores.max())


Array:
 [[85 92 78 96 88]
 [79 85 91 87 83]
 [92 88 95 91 89]
 [76 82 79 85 81]
 [88 91 87 93 90]]

Shape: (5, 5)
Dimentions: 2
Data type: int64
Total elements: 25

Mean (overall): 86.84
Min value: 76
Max value: 96


In [20]:
import numpy as np
student_scores = [
    [85, 92, 78, 96, 88],
    [79, 85, 91, 87, 83],
    [92, 88, 95, 91, 89],
    [76, 82, 79, 85, 81],
    [88, 91, 87, 93, 90]
])
# Convert to NumPy array
scores = np.array(student_scores)
# calculate each student"s average
student_averages = scores.mean(axis=1)
print("Student Averages:")
print(student_averages)
score.mean(axis=1)
score.mean(axis=2)
score.mean(axis=3)
score.mean(axis=4)
score.mean(axis=5)

SyntaxError: unmatched ')' (2444644611.py, line 8)

In [1]:
# Boolean array shwing scores above 90
import numpy as np
student_scores = [
    [85,92,78,96,88],
    [79,85,91,87,83],
    [92,88,95,91,89],
    [76,82,79,85,81],
    [88,91,87,93,90]
]
# convert to NumPy array
scores = np.array(student_scores)
# Boolean array for scores above 90
above_90 = scores >90
print("Boolean array (scores > 90):")
print(above_90)

Boolean array (scores > 90):
[[False  True False  True False]
 [False False  True False False]
 [ True False  True  True False]
 [False False False False False]
 [False  True False  True False]]


In [4]:
# Using slicing to get the first 3 students' scores on the last 2 tests
import numpy as np
student_scores = [
    [85,92,78,96,88],
    [79,85,91,87,83],
    [92,88,95,91,89],
    [76,82,79,85,81],
    [88,91,87,93,90]
]
scores = np.array(student_scores)
# first 3 students, last 2 tests
subset =scores[:3, -2:]
print("First 3 students' scores on last 2 tests:")
print(subset)

First 3 students' scores on last 2 tests:
[[96 88]
 [87 83]
 [91 89]]


In [ ]:
# Question 2
Analyze student performance across multiple subjects:
np. random.seed(456)
num_students, num_subjects = 50, 6
subject_names = ['Math', 'Science', 'English', 'History', 'Art', 'PE']
scores = np. random. randint(60, 100, (num_students, num_subjects))
Tasks:
1.	Find students who excel in STEM (Math + Science average > 90)
2.	Identify struggling students (any subject < 70) and which subjects they struggle with
3.	Find the most challenging subject (lowest average) and best performers in that subject


In [ ]:
import numpy as np


In [ ]:
# Question 3
Analyze a stock portfolio using NumPy's mathematical functions:
np.random.seed(789)
days = 252  # Trading days in a year
stocks = 5
# Simulate daily returns (percentage changes)
daily_returns = np.random.normal(0.001, 0.02, (days, stocks))  # Mean 0.1% daily return, 2% volatility
stock_names = ['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN']
initial_prices = np.array([150, 2800, 300, 800, 3200])
Tasks :
1.	Basic Analysis
o	Calculate cumulative returns for each stock
o	Find annualized volatility (standard deviation * sqrt(252))
o	Identify best and worst performing stocks
2.	Risk Metrics
o	Calculate Sharpe ratio (return/volatility) for each stock
o	Find maximum drawdown (largest peak-to-trough decline)
o	Calculate correlation matrix between stocks


In [16]:
import numpy as np
np.random.seed(789)
days = 252
stocks = 5
daily_returns = np.random.normal(0.001, 0.02, (days, stocks))
stock_names = ['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN']
initial_prices = np.array([150, 2800, 300, 800, 3200])
# cumulative return for each stock
cumulative_returns = np.prod(1 + daily_returns, axis=0) - 1
# identifying best and worst performing stocks
best_index = np.argmax(cumulative_returns)
worst_index = np.argmin(cumulative_returns)
     print("Cumulative Returns:")
for stock, ret in zip(stock_names,cumulative_returns):
     print(f"\nBest Performing Stock:
    {stock_names[[best_index]}
    (cumulative_returns[best_index]:'2%})")
     print(f"Worst Performing Stock:
    {stock_names[worst_index]}
    ({cumulative_returns[worst_index]:.2%})")


IndentationError: unexpected indent (793576453.py, line 13)